### ISSUE TITLE
Can I run the code on Window?

### ISSUE THREAD

**Issue by joyaskingquestions** [KaiDMML/FakeNewsNet#11]
Hi, I run `python main.py` on window command promt instead of `nohup python -m resource_server.app &> keys_server.out&`, but it returns the following error
`OverflowError: Python int too large to convert to C long`

Is it possible to run the code on window?or is it a must to use linux?
or the numbers exceeds `sys.maxsize`?

sorry if i have asked stupid question...
thanks!

**Comment by mdepak** [comment]
Hi @joyaskingquestions , 
According to this StackOverflow post  https://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072 the overflow error can occur. As we didn't encounter this issue in our setup, can you use fix from this accpted answer and  check if it helps .

**Comment by SaschaStenger** [comment]
Hi
i had the same Problem and if you put the fix into the util.py it fixes the issue.

**Comment by mdepak** [comment]
Thanks, @joyaskingquestions and @SaschaStenger for pointing out the issue. Fixed in https://github.com/KaiDMML/FakeNewsNet/commit/e2674a78a04642e949d02708231efdaf047574aa
