### ISSUE TITLE
Fail to access the twitter developer account

### ISSUE THREAD

**Issue by wuzhiyuan1996** [KaiDMML/FakeNewsNet#13]
Somebody for help!!!

Twitter API keys are essential for collecting data from Twitter.But my developer account application is not approved. And it seems that there is only one chance to apply for the account.
I wonder  if there is  a simpler way to obtain the data?

Thank you!

**Comment by channel960608** [comment]
I have tried and failed to apply for the development account too. It doesn't work until i found out that the account verified by a phone number from China is absolutely to be disproved. Change a Phone Number from other countries like United States. I will work!

**Comment by channel960608** [comment]
> Somebody for help!!!
> 
> Twitter API keys are essential for collecting data from Twitter.But my developer account application is not approved. And it seems that there is only one chance to apply for the account.
> I wonder if there is a simpler way to obtain the data?
> 
> Thank you!

I have tried and failed to apply for the development account too. It doesn't work until i found out that the account verified by a phone number from China is absolutely to be disproved. Change a Phone Number from other countries like United States. I will work!

**Comment by mdepak** [comment]
Closing this as it fixed and not related to the dataset.

**Comment by shaoqinzhang** [comment]
> > Somebody for help!!!
> > Twitter API keys are essential for collecting data from Twitter.But my developer account application is not approved. And it seems that there is only one chance to apply for the account.
> > I wonder if there is a simpler way to obtain the data?
> > Thank you!
> 
> I have tried and failed to apply for the development account too. It doesn't work until i found out that the account verified by a phone number from China is absolutely to be disproved. Change a Phone Number from other countries like United States. I will work!

Does it work?

**Comment by channel960608** [comment]
> > > Somebody for help!!!
> > > Twitter API keys are essential for collecting data from Twitter.But my developer account application is not approved. And it seems that there is only one chance to apply for the account.
> > > I wonder if there is a simpler way to obtain the data?
> > > Thank you!
> > 
> > 
> > I have tried and failed to apply for the development account too. It doesn't work until i found out that the account verified by a phone number from China is absolutely to be disproved. Change a Phone Number from other countries like United States. I will work!
> 
> Does it work?

Off Course
