### ISSUE TITLE
news_content incomplete due to unavailable URLs

### ISSUE THREAD

**Issue by mariekevh** [KaiDMML/FakeNewsNet#14]
Hi! 

I encounter an issue with the new_content database. I have collected the fake news content data of both Politifact and GossipCop. However, I noticed that a substantial number of URLs in politifact_fake.csv and gossipcop_fake.csv have become unavailable or have changed, making it impossible to collect these articles. This happend for 120 fake Politifact and 845 fake GossipCop articles.

I was wondering if there is any way to collect all the (fake) news content data as used in your latest dataset paper. 

Thank you!

Marieke

**Comment by mdepak** [comment]
Thanks for letting us know the problem. As mentioned in the paper we made use of web archive (http://web.archive.org/) to collect some of the missing web pages. I will add the code to download the  news articles from web archive if the original source is not found.

**Comment by mariekevh** [comment]
Thank you! Much appreciated. Do you have any idea when you will add this code?

**Comment by mdepak** [comment]
Added code to check web archive (http://web.archive.org/) for news articles in case if the actual news article URL is not available.
