### ISSUE TITLE
Helpp

### ISSUE THREAD

**Issue by danielfontenelle** [KaiDMML/FakeNewsNet#15]
Hello! Is it possible to set up another country?

**Comment by mdepak** [comment]
@danielfontenelle  Can you provide more details about the issue?

**Comment by danielfontenelle** [comment]
Hello,

For example; is it possible to filter news from only one country?

**Comment by mdepak** [comment]
The published dataset majorly composes of news articles related to Politics and entertainment media of the US. You can try using the approach mentioned in [FakeNewsNet](https://arxiv.org/pdf/1809.01286.pdf) paper to download data from similar fact-checking websites from other countries.
