### ISSUE TITLE
Is there the complete dataset ready to download?

### ISSUE THREAD

**Issue by alijrhi** [KaiDMML/FakeNewsNet#18]
Hi, 
According to some difficulties for crawling data, is there the complete dataset ready to download? or is it possible to upload the dataset for someone who has been able to successfully download it?

**Comment by mdepak** [comment]
One cannot disclose a large set of Tweets and users information as public under the Twitter policy. So the complete dataset cannot be published.

**Comment by alijrhi** [comment]
tnx, How about sending by an email? How big is it?

**Comment by alijrhi** [comment]
@mdepak Thanks, How about sending by an email? Is it possible?

**Comment by mdepak** [comment]
Sorry, the complete dataset cannot be disclosed as per Twitter Policy.
