### ISSUE TITLE
not able to download the data. could you plz help out how to download the data?

### ISSUE THREAD

**Issue by pyklsrinivas** [KaiDMML/FakeNewsNet#20]
showing the following information in data_collection.out file
nohup: ignoring input

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

**Comment by mdepak** [comment]
Verified use case and it works and hence closing issue.
