### ISSUE TITLE
Problem with crawling retweets.

### ISSUE THREAD

**Issue by rlleshi** [KaiDMML/FakeNewsNet#33]
The tweets are being crawled just fine but I am having troubles with retweets. I receive a _403 forbidden error_ or a _IndexError: list index out of range_ and cannot crawl anything. I can't quite figure out why this error is thrown at 
`retweets = connection.get_retweets(id=tweet.tweet_id, count=100, cursor=-1)`. Also there should be no problem with proving the twitter's API keys at _tweet_keys_file.txt_ file since the tweets themselves are being collected correctly whilst some of the retweets also do get collected. As a result most of retweets aren't being collected with the _.json_ file just containing `{"retweets": []}`. Some are though. Below are the full errors:

`ERROR:root:Exception in getting retweets for tweet id 960225064590327808 using connection <Twython: f9U42MLkHhl1V7o4aO1cGsNtf>
Traceback (most recent call last):
  File "FakeNewsNet\code\retweet_collection.py", line 19, in dum
p_retweets_job                                                                         | 144/165352 [15:34<18:07:51,  2.53it/s]
    retweets = connection.get_retweets(id=tweet.tweet_id, count=100, cursor=-1)
  File "Anaconda3\lib\site-packages\twython\endpoints.py", line 85, in get_retweets
    params=params)
  File "Anaconda3\lib\site-packages\twython\api.py", line 270, in get
    return self.request(endpoint, params=params, version=version)
  File "Anaconda3\lib\site-packages\twython\api.py", line 264, in request
    api_call=url)
  File "Anaconda3\lib\site-packages\twython\api.py", line 199, in _request
    retry_after=response.headers.get('X-Rate-Limit-Reset'))
twython.exceptions.TwythonError: Twitter API returned a 403 (Forbidden), Forbidden.
`

The other error:

`
ERROR:root:Exception in getting retweets for tweet id 920382448294400000 using connection None
Traceback (most recent call last):
  File "FakeNewsNet\code\retweet_collection.py", line 18, in dump
_retweets_job                                                                       | 2999/165352 [2:17:06<12:53:53,  3.50it/s]
    connection = twython_connector.get_twython_connection("get_retweet")
  File "FakeNewsNet\code\util\TwythonConnector.py", line 61, in g
et_twython_connection
    return self.streams[resource_index]
IndexError: list index out of range`

**Comment by SaschaStenger** [comment]
Hi @rlleshi. I Answered your question over here at #21
