### ISSUE TITLE
download simultaneously problems!

### ISSUE THREAD

**Issue by myrainbowandsky** [KaiDMML/FakeNewsNet#35]
Hi all,

I have ten 10 pairs of keys. 

1. Just put them into the tweet_Keys_file.txt? or should I have ten txt files with one pair in each file?

2.  How to set the config.json after finishing step1?

 "dump_location": "fakenewsnet_dataset",
  "dataset_dir": "../dataset",
  "tweet_keys_file": "resources/tweet_keys_file.txt",
  "num_process": 4,
  "num_twitter_keys": 1,

Regards

**Comment by mdepak** [comment]
With the updated code, to use multiple twitter keys configure the keys as an array of JSON objects in the `tweet_keys_file.json` file and configure the `num_twitter_keys` attribute in `config.json` file.
The `num_process` can be tuned depending on the CPU cores to speed up the download process.
