### ISSUE TITLE
How to see how many processes are running?

### ISSUE THREAD

**Issue by myrainbowandsky** [KaiDMML/FakeNewsNet#36]
I have set 28 pairs of keys in key jason file and 100 processes in configure jason file. The script is running. How to know the number of processes and keys running in fact? I am using Ubuntu 18.04 with python 3.6

**Comment by SaschaStenger** [comment]
Usually, if you call `ps -fu your-user-name` in the console, it will tell you, which processes you are currently running. 
Or if you are the only user on your machine `ps -ef | grep python` will show you all the python instances.

**Comment by myrainbowandsky** [comment]
It works. Thank you!
