### ISSUE TITLE
too many empty folders when downloading news articles

### ISSUE THREAD

**Issue by panicpan2000** [KaiDMML/FakeNewsNet#87]
I am trying to get the Twitter API key. So I only collect the news first.
I ran the code and set data_features_to_collect = ["news_articles"], but I encountered trouble. It seems that many URLs have been invalid and create empty folders without news content.json.
Is there any other alternative method to obtain the dataset?

**Comment by panicpan2000** [comment]
Using a proxy can solve part of the problem. However, some news actually no longer exists.

**Comment by rasel3413** [comment]
are you able to download the full dataset??can you please share it with me..? i am having so much trouble ...it taking so much time
